title: My Personal Blog
author: Sagar
email: sagar187@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog where I write about things that interest me.

# social links
github_username:  mr-sagarmandal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mr-sagarmandal.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Sass/SCSS settings
sass:
  style: compressed
  sass_dir: _sass

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
